### ISSUE TITLE
Create a package set repo?

### ISSUE THREAD

**Issue by paf31** [purerl/purescript#1]
It might be interesting to create a separate package set repo for `purerl` packages. That way, users can easily set up a `psc-package` config and just change the Git URL to point to that repo, and get started.

**Comment by nwolverson** [comment]
It's on it's way! I have a package set under construction but paused as I'm unable to verify package still build and work. Cleverly merged change from purescript master around 0.10, updates to all packages, and implemented optimisations in the Erlang backend around the same time.

(PSA: If you use `pserlc` just now pass `--no-opts`, it's broken in multiple ways because (at least) I am stupid)

**Comment by nwolverson** [comment]
https://github.com/purerl/package-sets
