### ISSUE TITLE
[question] How to start helping out with this project?

### ISSUE THREAD

**Issue by toraritte** [purerl/purescript#10]
I am more familiar with Erlang/Elixir (not an expert by any means) and just starting out with PureScript and Haskell, but I do love the type system and principled approach of the latter better.

**What would your recommendation be to look for someone who would like to contribute?** That is, code in this project, or other resources that you've found helpful, however tangential. I know this question is very general, and any info would be useful.

Thanks, and thank you also for all the work you you've put into this!

**Comment by nwolverson** [comment]
Hi,

I think fundamentally the best thing to do is to actually use it and see what's missing, for you, what you think could be better, etc.

As a bit of a preview, we have a couple of more opinionated wrapper libraries for OTP behaviours and Cowboy servers, which are currently not public but should be opened up in the future, so if that's something you'd want maybe look out for that.

I can't see a link to [my dev blog](https://nwolverson.uk/devlog/) on the README here, maybe I should add that, I don't write much but maybe there is something useful there. Otherwise I'd just suggest looking at stuff in the purerl github org, you can see what's in the package set and dive into that.

Feel free to hit me up on the FP slack if I can be of use.
