### ISSUE TITLE
Version Management

### ISSUE THREAD

**Issue by toastal** [purerl/purescript#13]
Like the mainline PureScript compiler on NPM (or Hex in this case?), it would be nice to be able to install a specific version for a project through the project's package manager to keep versions pinned and updating more portable.

How are people normally doing this now? Docker? Nix? asdf-vm?

**Comment by toastal** [comment]
I got something very rough, but works for `asdf-vm` here using this repo: https://gitlab.com/toastal/asdf-purerl

**Comment by nwolverson** [comment]
Likely nix is a good contender, or of course whatever one uses to version random binaries already. Since we're in the position of being somewhat "between" 2 ecosystems I can't really commit to much more than making binaries available.

That said, [purerl](https://github.com/purerl/purerl)  is now a standalone backend and I'm deprecating this compiler-fork repository (along with suggesting spago as a build tool which will support alternate backends). Hopefully in the future this might somewhat alleviate the versioning issue, at least separating it from the mainline compiler versions tied to language changes etc.

Related to that see https://github.com/purerl/nixpkgs-purerl
