### ISSUE TITLE
Random produces same value

### ISSUE THREAD

**Issue by Rockfordal** [purerl/purescript#2]
main :: forall e. Eff (console :: CONSOLE, random :: RANDOM | e) Unit
main = randomInt 1 100 >>= logShow

i get 45 every time, even if i delete ebin, output and make again
(had to change set to erl-0.10.7 for psc-package to pull down random, and add main@ps:main in Makefile for it to build)

**Comment by kritzcreek** [comment]
![](https://imgs.xkcd.com/comics/random_number.png)

**Comment by nwolverson** [comment]
Relevant code is here: https://github.com/purerl/purescript-random/blob/master/src/Control/Monad/Eff/Random.erl#L4

The generator is never seeded so see http://erlang.org/doc/man/random.html#seed-0.

I wonder if a specific random wrapper should be added instead of just the fork for purescript-random, exposing seed etc - or just add some arbitrary seeding in purescript-random

**Comment by Rockfordal** [comment]
my ide say:  the 'random' module is deprecated; use the 'rand' module instead

**Comment by Rockfordal** [comment]
works when i change to rand for me
i made pull request to purescript-random
